INSERT IGNORE INTO rol (ID, DESCRIPTION, ROLE) VALUES (1, "ROL ADMINISTRADOR", "ADMIN");
INSERT IGNORE INTO rol VALUES (2, "ROL OWNER","OWNER");
INSERT IGNORE INTO rol VALUES (3, "ROL CAMARERO","WAITER");
INSERT IGNORE INTO rol VALUES (4, "ROL CAJERO","CASHIER");
INSERT IGNORE INTO rol VALUES (5,  "ROL COCINERO","COOKER");

