INSERT IGNORE INTO restaurante.rol VALUES (1, "ADMIN", "ROL ADMINISTRADOR");
INSERT IGNORE INTO restaurante.rol VALUES (2, "OWNER", "ROL OWNER");
INSERT IGNORE INTO restaurante.rol VALUES (3, "WAITER", "ROL CAMARERO");
INSERT IGNORE INTO restaurante.rol VALUES (4, "CASHIER", "ROL CAJERO");
INSERT IGNORE INTO restaurante.rol VALUES (5, "COOKER", "ROL COCINERO");