version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/app/src:rw,cached
    ports:
      - 8080:8081
    depends_on:
      - db
    entrypoint: [ "java","-jar","click2eat.jar" ]
    tty: true
  db:
    image: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - java-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  java-db:
networks:
  default:
    driver: bridge