name: Deploy pro

on:
  workflow_run:
    workflows:
      - build
      - test
    types:
      - completed
jobs:
  deploy-pro:
    runs-on: self-hosted
    environment: pro
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build with Maven
        run: mvn clean package

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

      - name: Show extracted Maven project version
        run: echo ${{ steps.project.outputs.version }}

      - name: Copy via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "target/click2eat-${{ steps.project.outputs.version }}.jar, docker/docker-compose-servidor.yaml"
          target: "app/click2eat-backend/"

      - name: Renaming file in server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script:  cd /home/ubuntu/app/click2eat-backend/ && mv target/click2eat-${{ steps.project.outputs.version }}.jar click2eat.jar  
            && rm -rf target/ && mv docker/docker-compose-servidor.yaml docker-compose.yaml
            && rm -rf docker/ && docker compose down  && docker compose up -d
