name: Prueba

on:
  push:
    branches-ignore:
      - config
jobs:
  project-build:
    runs-on: self-hosted
    environment: pro
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven

      - name: copy application.properties
        run: cp src/main/resources/application-example.properties src/main/resources/application.properties

      - name: Read/Write Properties File
        uses: kurt-code/gha-properties@v0.0.1
        id: read-properties
        with:
          operation: 'write'
          file-path: 'src/main/resources/application.properties'
          key-value-pairs: |
            {
              "spring.datasource.url": "${{ secrets.DATASOURCE_URL }}",
              "spring.datasource.username": "${{ secrets.DATASOURCE_USERNAME }}",
              "spring.datasource.password": "${{ secrets.DATASOURCE_PASSWORD }}",
              "spring.mail.username": "${{ secrets.MAIL_USERNAME }}",
              "spring.mail.password": "${{ secrets.MAIL_PASSWORD }}"
            
            }

      - name: Read properties
        run: echo src/main/resources/application.properties

      - name: Set up Firebase service account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > src/main/resources/firebase-service-account.json

  

      - name: Build with Maven
        run: mvn clean package

