name: Test

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  test:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed 2'